import type { AuthorProfile } from './corpus-types';

export const REFERENCE_AUTHORS: AuthorProfile[] = [
  {
    id: 'camoes',
    name: 'Luís de Camões',
    period: 'Renascimento (séc. XVI)',
    movement: 'Classicismo',
    knownTones: ['epico', 'lirico', 'reflexivo', 'melancolico'],
    features: {
      lexicalRichness: 0.65,
      averageWordLength: 5.2,
      averageSyllablesPerWord: 2.4,
      formalRegisterScore: 0.85,
      figureDensity: 0.4,
      rhymeConsistency: 0.95,
      metricalConsistency: 0.9,
      enjambementRatio: 0.15,
      soundDeviceDensity: 0.3,
      abstractRatio: 0.25,
      concreteRatio: 0.3,
      emotionCompoundScore: 0.1,
      conjunctionFrequency: 0.12,
      adjectiveRatio: 0.08,
      verbRatio: 0.14,
      nounRatio: 0.22,
      pronounRatio: 0.06,
    },
    vocabularySignature: ['amor', 'dor', 'fortuna', 'tempo', 'mundo', 'engano', 'desejo', 'lágrima', 'saudade', 'fermosura', 'brando', 'cruel', 'sublime', 'eterno', 'humilde', 'ousado', 'perigo', 'ventura', 'fado', 'sina'],
    preferredForms: ['soneto', 'decassilabo', 'oitava'],
    description: 'Lírico amoroso e épico nacional. Sonetos petrarquianos, decassílabos heroicos. Tensão entre paixão e razão.',
  },
  {
    id: 'pessoa',
    name: 'Fernando Pessoa',
    period: 'Modernismo (séc. XX)',
    movement: 'Modernismo / Heteronímia',
    knownTones: ['reflexivo', 'filosofico', 'intimista', 'conciso', 'visionario'],
    features: {
      lexicalRichness: 0.72,
      averageWordLength: 5.0,
      averageSyllablesPerWord: 2.2,
      formalRegisterScore: 0.7,
      figureDensity: 0.35,
      rhymeConsistency: 0.6,
      metricalConsistency: 0.5,
      enjambementRatio: 0.35,
      soundDeviceDensity: 0.25,
      abstractRatio: 0.35,
      concreteRatio: 0.2,
      emotionCompoundScore: -0.1,
      conjunctionFrequency: 0.14,
      adjectiveRatio: 0.09,
      verbRatio: 0.16,
      nounRatio: 0.18,
      pronounRatio: 0.1,
    },
    vocabularySignature: ['ser', 'nada', 'sonho', 'vida', 'alma', 'deus', 'fim', 'infinito', 'canseira', 'passado', 'falso', 'verdade', 'fingimento', 'dor', 'vontade', 'consciência', 'fragmento', 'absurdo', 'sentir', 'pensar'],
    preferredForms: ['verso-livre', 'decassilabo', 'soneto', 'oda'],
    description: 'Poesia metafísica e fragmentária. Heterônimos com estilos contrastantes. Alto teor de abstração e reflexão existencial.',
  },
  {
    id: 'drummond',
    name: 'Carlos Drummond de Andrade',
    period: 'Modernismo (séc. XX)',
    movement: 'Modernismo brasileiro',
    knownTones: ['reflexivo', 'satirico', 'intimista', 'filosofico', 'melancolico'],
    features: {
      lexicalRichness: 0.68,
      averageWordLength: 5.1,
      averageSyllablesPerWord: 2.3,
      formalRegisterScore: 0.6,
      figureDensity: 0.3,
      rhymeConsistency: 0.4,
      metricalConsistency: 0.3,
      enjambementRatio: 0.45,
      soundDeviceDensity: 0.2,
      abstractRatio: 0.3,
      concreteRatio: 0.25,
      emotionCompoundScore: -0.15,
      conjunctionFrequency: 0.13,
      adjectiveRatio: 0.07,
      verbRatio: 0.15,
      nounRatio: 0.2,
      pronounRatio: 0.08,
    },
    vocabularySignature: ['família', 'sentimento', 'mundo', 'tempo', 'mágoa', 'pedra', 'coração', 'poema', 'vida', 'noite', 'amor', 'gente', 'cidade', 'casa', 'rua', 'espanto', 'anjo', 'tristeza', 'fim', 'osso'],
    preferredForms: ['verso-livre', 'poema', 'odes'],
    description: 'Ironia e lirismo existencial. Cotidiano elevado ao universal. Linguagem coloquial entremeada de reflexão profunda.',
  },
  {
    id: 'bandeira',
    name: 'Manuel Bandeira',
    period: 'Modernismo (séc. XX)',
    movement: 'Modernismo brasileiro',
    knownTones: ['lirico', 'melancolico', 'nostalgico', 'intimista', 'satirico'],
    features: {
      lexicalRichness: 0.62,
      averageWordLength: 4.8,
      averageSyllablesPerWord: 2.1,
      formalRegisterScore: 0.55,
      figureDensity: 0.25,
      rhymeConsistency: 0.5,
      metricalConsistency: 0.4,
      enjambementRatio: 0.3,
      soundDeviceDensity: 0.25,
      abstractRatio: 0.2,
      concreteRatio: 0.3,
      emotionCompoundScore: -0.2,
      conjunctionFrequency: 0.11,
      adjectiveRatio: 0.06,
      verbRatio: 0.13,
      nounRatio: 0.21,
      pronounRatio: 0.07,
    },
    vocabularySignature: ['vida', 'morte', 'poesia', 'sonho', 'passado', 'infância', 'noite', 'estrela', 'céu', 'mar', 'vento', 'sombra', 'doce', 'triste', 'alegre', 'sol', 'lua', 'corpo', 'alma', 'saudade'],
    preferredForms: ['verso-livre', 'redondilha', 'soneto'],
    description: 'Lirismo da simplicidade. Temas da morte e da infância. Tom coloquial com grande musicalidade.',
  },
  {
    id: 'machado',
    name: 'Machado de Assis (poesia)',
    period: 'Realismo (séc. XIX)',
    movement: 'Realismo / Parnasianismo',
    knownTones: ['reflexivo', 'satirico', 'filosofico', 'conciso'],
    features: {
      lexicalRichness: 0.7,
      averageWordLength: 5.3,
      averageSyllablesPerWord: 2.5,
      formalRegisterScore: 0.88,
      figureDensity: 0.3,
      rhymeConsistency: 0.9,
      metricalConsistency: 0.85,
      enjambementRatio: 0.12,
      soundDeviceDensity: 0.2,
      abstractRatio: 0.28,
      concreteRatio: 0.22,
      emotionCompoundScore: 0.0,
      conjunctionFrequency: 0.1,
      adjectiveRatio: 0.09,
      verbRatio: 0.12,
      nounRatio: 0.24,
      pronounRatio: 0.05,
    },
    vocabularySignature: ['vida', 'mundo', 'tempo', 'amor', 'dor', 'sonho', 'glória', 'fama', 'morte', 'engano', 'céu', 'terra', 'homem', 'razão', 'fortuna', 'destino', 'acaso', 'nada', 'tudo', 'além'],
    preferredForms: ['soneto', 'decassilabo'],
    description: 'Poesia parnasiana formal com ironia sutil. Métrica rigorosa, vocabulário erudito, ceticismo filosófico.',
  },
  {
    id: 'quaresma',
    name: 'Alberto Caeiro (heter. Pessoa)',
    period: 'Modernismo (séc. XX)',
    movement: 'Sensacionismo',
    knownTones: ['lirico', 'conciso', 'jubiloso', 'reflexivo'],
    features: {
      lexicalRichness: 0.58,
      averageWordLength: 4.6,
      averageSyllablesPerWord: 2.0,
      formalRegisterScore: 0.45,
      figureDensity: 0.15,
      rhymeConsistency: 0.2,
      metricalConsistency: 0.2,
      enjambementRatio: 0.5,
      soundDeviceDensity: 0.15,
      abstractRatio: 0.12,
      concreteRatio: 0.45,
      emotionCompoundScore: 0.3,
      conjunctionFrequency: 0.09,
      adjectiveRatio: 0.05,
      verbRatio: 0.11,
      nounRatio: 0.25,
      pronounRatio: 0.06,
    },
    vocabularySignature: ['ver', 'olhar', 'natureza', 'pedra', 'árvore', 'flor', 'rio', 'monte', 'real', 'pensar', 'sentir', 'coisa', 'campo', 'sol', 'luz', 'verde', 'azul', 'branco', 'simples', 'ser'],
    preferredForms: ['verso-livre', 'poema'],
    description: 'Poesia sensacionista. Rejeição da metafísica. Olhar direto sobre a natureza. Léxico concreto e simples.',
  },
  {
    id: 'macedo',
    name: 'José de Alencar (poesia)',
    period: 'Romantismo (séc. XIX)',
    movement: 'Romantismo brasileiro',
    knownTones: ['lirico', 'romantico', 'epico', 'saudoso'],
    features: {
      lexicalRichness: 0.6,
      averageWordLength: 4.9,
      averageSyllablesPerWord: 2.3,
      formalRegisterScore: 0.75,
      figureDensity: 0.35,
      rhymeConsistency: 0.85,
      metricalConsistency: 0.8,
      enjambementRatio: 0.1,
      soundDeviceDensity: 0.3,
      abstractRatio: 0.2,
      concreteRatio: 0.35,
      emotionCompoundScore: 0.2,
      conjunctionFrequency: 0.1,
      adjectiveRatio: 0.1,
      verbRatio: 0.13,
      nounRatio: 0.2,
      pronounRatio: 0.08,
    },
    vocabularySignature: ['amor', 'natureza', 'índio', 'pátria', 'terra', 'selva', 'rio', 'lua', 'estrela', 'noite', 'sonho', 'liberdade', 'canto', 'glória', 'ventura', 'virgem', 'selvagem', 'floresta', 'céu', 'mar'],
    preferredForms: ['soneto', 'decassilabo', 'poema narrativo'],
    description: 'Poesia romântica indianista e lírica. Natureza exuberante, idealização do amor e da pátria.',
  },
  {
    id: 'goncalves-dias',
    name: 'Gonçalves Dias',
    period: 'Romantismo (séc. XIX)',
    movement: 'Romantismo brasileiro',
    knownTones: ['lirico', 'romantico', 'saudoso', 'epico', 'melancolico'],
    features: {
      lexicalRichness: 0.63,
      averageWordLength: 5.0,
      averageSyllablesPerWord: 2.3,
      formalRegisterScore: 0.78,
      figureDensity: 0.38,
      rhymeConsistency: 0.88,
      metricalConsistency: 0.82,
      enjambementRatio: 0.12,
      soundDeviceDensity: 0.35,
      abstractRatio: 0.2,
      concreteRatio: 0.3,
      emotionCompoundScore: -0.1,
      conjunctionFrequency: 0.11,
      adjectiveRatio: 0.09,
      verbRatio: 0.14,
      nounRatio: 0.19,
      pronounRatio: 0.07,
    },
    vocabularySignature: ['amor', 'pátria', 'terra', 'natureza', 'noite', 'mar', 'ventura', 'saudade', 'dor', 'pranto', 'canto', 'índio', 'floresta', 'belo', 'virgem', 'sol', 'lua', 'estrela', 'vida', 'morte'],
    preferredForms: ['soneto', 'redondilha', 'poema lírico'],
    description: 'Poesia romântica nacionalista. Exaltação da natureza brasileira e do amor pátrio. Lirismo saudosista.',
  },
  {
    id: 'augusto-dos-anjos',
    name: 'Augusto dos Anjos',
    period: 'Pré-Modernismo (séc. XX)',
    movement: 'Pré-Modernismo',
    knownTones: ['sombrio', 'grotesco', 'filosofico', 'melancolico'],
    features: {
      lexicalRichness: 0.75,
      averageWordLength: 5.5,
      averageSyllablesPerWord: 2.6,
      formalRegisterScore: 0.9,
      figureDensity: 0.5,
      rhymeConsistency: 0.92,
      metricalConsistency: 0.88,
      enjambementRatio: 0.08,
      soundDeviceDensity: 0.2,
      abstractRatio: 0.4,
      concreteRatio: 0.15,
      emotionCompoundScore: -0.6,
      conjunctionFrequency: 0.15,
      adjectiveRatio: 0.12,
      verbRatio: 0.18,
      nounRatio: 0.16,
      pronounRatio: 0.04,
    },
    vocabularySignature: ['verme', 'poda', 'necrose', 'carniça', 'aborto', 'monstro', 'lodo', 'treva', 'espectro', 'podridão', 'tumba', 'cova', 'nada', 'ser', 'matéria', 'cósmico', 'átomo', 'energia', 'morte', 'dor'],
    preferredForms: ['soneto', 'decassilabo'],
    description: 'Poesia grotesca e existencial. Vocabulário científico e macabro. Metáforas biológicas da decomposição. Tom pessimista radical.',
  },
  {
    id: 'quaresma-pessoa',
    name: 'Ricardo Reis (heter. Pessoa)',
    period: 'Modernismo (séc. XX)',
    movement: 'Neoclassicismo',
    knownTones: ['filosofico', 'conciso', 'reflexivo', 'melancolico', 'sagrado'],
    features: {
      lexicalRichness: 0.7,
      averageWordLength: 5.0,
      averageSyllablesPerWord: 2.4,
      formalRegisterScore: 0.85,
      figureDensity: 0.2,
      rhymeConsistency: 0.85,
      metricalConsistency: 0.9,
      enjambementRatio: 0.1,
      soundDeviceDensity: 0.15,
      abstractRatio: 0.35,
      concreteRatio: 0.2,
      emotionCompoundScore: -0.2,
      conjunctionFrequency: 0.08,
      adjectiveRatio: 0.1,
      verbRatio: 0.12,
      nounRatio: 0.2,
      pronounRatio: 0.04,
    },
    vocabularySignature: ['fado', 'deus', 'ser', 'nada', 'vida', 'morte', 'sabedoria', 'sorte', 'destino', 'hora', 'breve', 'instante', 'poder', 'querer', 'saber', 'gozar', 'fugir', 'esquecer', 'lembrar', 'odia'],
    preferredForms: ['oda', 'soneto', 'decassilabo'],
    description: 'Poesia neoclássica com epicurismo estoico. Horaciana, busca da ataraxia. Métrica rigorosa, tom contido.',
  },
  {
    id: 'cross',
    name: 'Álvaro de Campos (heter. Pessoa)',
    period: 'Modernismo (séc. XX)',
    movement: 'Futurismo / Sensacionismo',
    knownTones: ['visionario', 'epico', 'satirico', 'filosofico', 'jubiloso'],
    features: {
      lexicalRichness: 0.74,
      averageWordLength: 5.3,
      averageSyllablesPerWord: 2.3,
      formalRegisterScore: 0.6,
      figureDensity: 0.45,
      rhymeConsistency: 0.3,
      metricalConsistency: 0.2,
      enjambementRatio: 0.5,
      soundDeviceDensity: 0.3,
      abstractRatio: 0.3,
      concreteRatio: 0.25,
      emotionCompoundScore: 0.0,
      conjunctionFrequency: 0.16,
      adjectiveRatio: 0.11,
      verbRatio: 0.17,
      nounRatio: 0.17,
      pronounRatio: 0.09,
    },
    vocabularySignature: ['máquina', 'civilização', 'moderno', 'rua', 'multidão', 'fábrica', 'vapor', 'eletricidade', 'força', 'velocidade', 'imenso', 'tudo', 'nada', 'canseira', 'tédio', 'vida', 'viver', 'sentir', 'pensar', 'ação'],
    preferredForms: ['verso-livre', 'ode', 'poema extenso'],
    description: 'Poesia futurista e sensacionista. Exaltação da modernidade e da máquina. Tom épico e ufanista alternado com tédio existencial.',
  },
  {
    id: 'bilac',
    name: 'Olavo Bilac',
    period: 'Parnasianismo (séc. XIX-XX)',
    movement: 'Parnasianismo',
    knownTones: ['lirico', 'conciso', 'romantico', 'epico'],
    features: {
      lexicalRichness: 0.68,
      averageWordLength: 5.1,
      averageSyllablesPerWord: 2.4,
      formalRegisterScore: 0.88,
      figureDensity: 0.3,
      rhymeConsistency: 0.95,
      metricalConsistency: 0.92,
      enjambementRatio: 0.08,
      soundDeviceDensity: 0.35,
      abstractRatio: 0.22,
      concreteRatio: 0.3,
      emotionCompoundScore: 0.1,
      conjunctionFrequency: 0.09,
      adjectiveRatio: 0.1,
      verbRatio: 0.12,
      nounRatio: 0.22,
      pronounRatio: 0.05,
    },
    vocabularySignature: ['língua', 'pátria', 'amor', 'arte', 'poesia', 'musa', 'glória', 'formosura', 'ouro', 'prata', 'mármore', 'jóia', 'cristal', 'estrela', 'luz', 'céu', 'sonho', 'beleza', 'eterno', 'perfeito'],
    preferredForms: ['soneto', 'decassilabo', 'poema parnasiano'],
    description: 'Poesia parnasiana. Culto à forma e à beleza. Métrica perfeita, rima rica, vocabulário lapidar.',
  },
];

export function getReferenceAuthor(id: string): AuthorProfile | undefined {
  return REFERENCE_AUTHORS.find(a => a.id === id);
}

export function getAuthorsByTone(tone: string): AuthorProfile[] {
  const toneLower = tone.toLowerCase();
  return REFERENCE_AUTHORS.filter(a =>
    a.knownTones.some(t => t.toLowerCase() === toneLower),
  );
}

export function getAllTones(): string[] {
  const tones = new Set<string>();
  for (const author of REFERENCE_AUTHORS) {
    for (const tone of author.knownTones) {
      tones.add(tone);
    }
  }
  return [...tones].sort();
}
