export const FORMAL_MARKERS = new Set([
  'portanto', 'entretanto', 'todavia', 'contudo', 'outrossim',
  'ademais', 'outrem', 'alhures', 'doravante',
  'outrora', 'sobejo', 'escopro', 'lusco-fusco', 'alva',
  'conquanto', 'destarte', 'dessarte', 'sobreditos',
  'supracitado', 'sobredito', 'epígrafe', 'epigrafe',
  'consoante', 'mormente', 'sobremaneira',
  'vossemecê', 'vossa', 'vosso', 'vossos', 'vossas',
  'merce', 'imperioso', 'imprescindível', 'imprescindivel',
  'notório', 'notoria', 'consubstanciado', 'consubstanciada',
  'hodierno', 'hodierna', 'litúrgico', 'liturgico',
  'sacrossanto', 'sacrossanta',
  'ressalvado', 'ressalvada',
  'malgrado', 'tampouco',
  'porquanto',
  'a saber', 'verbis', 'ipsis litteris',
  'data venia', 'data vênia',
  'com efeito',
  'dessa feita', 'desta feita',
  'deveras', 'sobreleva',
  'venerando', 'veneranda',
  'egrégio', 'egregio', 'egrégia', 'egregia',
  'ilustríssimo', 'ilustrissimo', 'ilustríssima', 'ilustrissima',
  'excelentíssimo', 'excelentissimo',
  'douto', 'douta', 'insigne',
  'preclaro', 'preclara', 'ímprobo', 'improba',
  'abnegado', 'abnegada', 'probo', 'proba',
  'retidão', 'retidao', 'retitude',
  'proceder', 'procedimento',
  'exordial',
  'mandato', 'mandatário', 'mandataria',
  'despacho', 'sentença', 'sentenca',
  'acórdão', 'acordao', 'jurisprudência', 'jurisprudencia',
  'parecer', 'relatório', 'relatorio',
  'voto', 'vista', 'diligência', 'diligencia',
  'intimação', 'intimacao', 'citação', 'citacao',
  'notificação', 'notificacao',
  'convocação', 'convocacao',
  'desse jeito', 'desse modo',
  'dessa maneira', 'dessa forma',
  'sobejamente',
  'por derradeiro', 'em derradeiro',
  'ao cabo', 'ao fim e ao cabo',
  'em suma', 'em síntese', 'em sintese',
  'via de regra',
  'não raro', 'nao raro',
  'não obstante', 'nao obstante',
  'tanto é assim que', 'tanto e assim que',
  'por sinal',
  'aliás', 'alias',
  'demais', 'igualmente',
  'doutrina', 'doutrinário', 'doutrinaria',
  'teor',
  'escopo',
  'cerne',
  'âmago', 'amago',
  'fulcro',
  'liame',
  'vínculo', 'vinculo', 'nexo',
  'intuito', 'intento',
  'desiderato',
  'condão', 'condao',
  'quilate',
  'estirpe',
  'casta',
  'prole',
  'descendência', 'descendencia',
  'linhagem',
  'combalido', 'combalida',
  'decrepitude',
  'senectude',
  'obsolescência', 'obsolescencia',
  'obsoleto', 'obsoleta',
  'caduco', 'caduca',
  'peremptório', 'peremptorio',
  'inconcuso', 'inconcussa',
  'indubitável', 'indubitavel', 'indubitavelmente',
  'inexorável', 'inexoravel', 'inexoravelmente',
  'inconteste',
  'insofismável', 'insofismavel',
  'irretorquível', 'irretorquivel',
  'irrefragável', 'irrefragavel',
  'inilidível', 'inilidivel',
  'nada obstante',
  'sobremodo',
  'sobremaneira',
  'assaz',
  'tão_somente', 'tãosomente',
  'tão somente',
  'tampouco',
  'quão',
  'comquanto',
  'entrementes',
  'não_obstante',
  'não obstante',
  'nao obstante',
  'obstante',
  'haja_vista',
  'haja vista',
  'hajam vista',
  'isto_é',
  'isto é',
  'isto e',
  'ou seja',
  'ou_melhor',
  'ou melhor',
  'por_outro_lado',
  'por outro lado',
  'não obstante',
  'sob_pena_de',
  'sob pena de',
  'em_se_tratando_de',
  'em se tratando de',
  'no_que_tange_a',
  'no que tange a',
  'no_tocante_a',
  'no tocante a',
  'com_vistas_a',
  'com vistas a',
  'à_luz_de',
  'à luz de',
  'a luz de',
  'faz_se_mister',
  'faz-se mister',
  'cumpre_salientar',
  'cumpre salientar',
  'importa_ressaltar',
  'importa ressaltar',
  'sobreleva_notar',
  'sobreleva notar',

  'destarte',
  'dessa feita',
  'desta feita',
  'dessarte',
  'outrossim',
  'outra_sorte',
  'do mesmo modo',

  'tergiversar',
  'concatenar',
  'corroborar',
  'elencar',
  'explanar',
  'empreender',
  'preconizar',
  'fomentar',
  'viabilizar',
  'coadunar',
  'sopesar',
  'contemplar',
  'tangenciar',
  'assentar',
  'dissaborear',
  'debelar',
  'dissuadir',
  'aferir',
  'suscitar',
  'cognominar',
  'perquirir',
  'esposar',
  'advir',
  'adstringir',
  'aquiescer',
  'condescender',
  'compadecer',
  'desiderar',
  'conjeturar',
  'infletir',
  'perlustrar',
  'exsurgir',
  'obnubilar',
  'esmaecer',
  'fenececer',
  'refluir',
  'consubstanciar',
  'exordial',
  'procuração',
  'supedâneo',
  'suprassumo',
  'condão',
  'escopo',
  'desiderato',
  'subterfúgio',
  'subterfugio',
  'conjectura',
  'conjetura',
  'prerrogativa',
  'injunção',
  'cominação',
  'cominacao',
  'admoestação',
  'admoestacao',
  'lídimo',
  'lídima',
  'lidimo',
  'lidima',
  'hígido',
  'higido',
  'hígida',
  'higida',
  'insípido',
  'insipido',
  'insípida',
  'insipida',
  'mavioso',
  'maviosa',
  'pachorrento',
  'pachorrenta',
  'prófugo',
  'profugo',
  'prófuga',
  'profuga',
  'refugo',
  'sórdido',
  'sordido',
  'sórdida',
  'sordida',
  'torpe',
  'torpes',
  'vitando',
  'vitanda',
  'vitanda',
  'vitando',
  'vitandos',

  'consoante',
  'mormente',
  'sobremaneira',
  'outrossim',
  'ademais',
  'outrem',
  'alhures',
  'doravante',
  'outrora',
  'sobejo',
  'sobejamente',
  'alva',
  'lusco-fusco',
  'escopro',
  'malgrado',
  'tampouco',

  'indubitável', 'indubitavel',
  'indubitavelmente',
  'inexorável', 'inexoravel',
  'inexoravelmente',
  'insofismável', 'insofismavel',
  'irretorquível', 'irretorquivel',
  'irrefragável', 'irrefragavel',
  'inilidível', 'inilidivel',
  'inconteste',
  'inconcuso', 'inconcussa',
  'combalido', 'combalida',
  'caduco', 'caduca',
  'peremptório', 'peremptorio',
  'peremptória', 'peremptoria',
  'obsoleto', 'obsoleta',
  'obstante',
  'sobredito', 'sobredita',
  'supracitado', 'supracitada',

  'com efeito',
  'na verdade',
  'de fato',
  'em verdade',
  'não obstante',
  'nada obstante',
  'tanto é assim que',
  'tanto e assim que',
  'ao contrário de',
  'ao contrario de',
  'diversamente de',
  'em contrapartida',
  'em contraste com',
  'via de regra',
  'em regra',
  'em geral',

  'em suma',
  'em síntese', 'em sintese',
  'em resumo',
  'em conclusão', 'em conclusao',
  'por fim',
  'finalmente',
  'em derradeiro',
  'por derradeiro',
  'ao cabo',
  'ao fim e ao cabo',
  'em última análise', 'em ultima analise',
  'em última instância', 'em ultima instancia',
  'em último caso', 'em ultimo caso',
  'em caso extremo',
  'em caso limite',
  'quando muito',
  'quando nada',
  'quando menos',
  'no mínimo', 'no minimo',
  'no máximo', 'no maximo',

  'a propósito', 'a proposito',
  'aliás', 'alias',
  'por sinal',
  'ademais',
  'demais',
  'igualmente',
  'do mesmo modo',
  'da mesma forma',
  'da mesma maneira',
]);

export const INFORMAL_MARKERS = new Set([
  'tá', 'pra', 'pro', 'cê', 'né', 'tô', 'vô', 'tava',
  'numa', 'duma', 'mode', 'cuma', 'daí', 'dai',
  'aí', 'ai', 'ih', 'ah', 'ué', 'poxa',
  'mermo', 'trem', 'bão', 'sô', 'sôr',
  'beleza', 'brother', 'mana', 'miga', 'migo',
  'tipo', 'tlgd', 'se liga', 'vacilou', 'vacilo',
  'trampo', 'parada', 'nego', 'minina', 'mininu',
  'caba', 'muié', 'home', 'fessô', 'fessora',
  'oxente', 'visse', 'óia', 'ói', 'uai', 'eita',
  'nóis', 'nois', 'ocê', 'oces', 'cês', 'ces',
  'vixe', 'nossa', 'caraca', 'caramba',
  'pô', 'po', 'bá', 'bah',
  'tri', 'trilegal', 'da hora',
  'supimpa', 'sinistro', 'sinistra',
  'maneiro', 'maneira', 'bacana',
  'legal', 'fixe', 'giro', 'giro',
  'bué', 'bué', 'bué',
  'fixola', 'top', 'topzera',
  'brabo', 'braba', 'monstro',
  'monstra', 'fera', 'fodástico', 'fodastico',
  'foda', 'foda', 'foda-se', 'foda se',
  'porra', 'merda', 'bosta', 'cacete',
  'caralho', 'pau', 'rola', 'buceta',
  'arrombado', 'arrombada', 'filho da puta',
  'desgraçado', 'desgracado', 'desgraçada', 'desgracada',
  'babaca', 'otário', 'otario', 'otária', 'otaria',
  'idiota', 'imbecil', 'retardado', 'retardada',
  'maluquete', 'doido', 'doida', 'doidão', 'doidona',
  'véio', 'véia', 'veio', 'veia',
  'guri', 'guria', 'piá', 'pia',
  'moleque', 'moleca', 'pirralho', 'pirralha',
  'nego', 'nega', 'criolo', 'criola',
  'brother', 'brothers', 'mano', 'mana',
  'parceiro', 'parceira', 'parça', 'parcas',
  'amigão', 'amigona', 'chegado', 'chegada',
  'coé', 'coe', 'qualé', 'quale',
  'tô ligado', 'to ligado', 'tô ligada', 'to ligada',
  'entendeu', 'entende', 'saca', 'sacou',
  'tipo assim', 'tipo', 'assim tipo',
  'sei lá', 'sei la',
  'oravida', 'oravida',
  'véi', 'vei', 'cara',
  'mina', 'gata', 'gato', 'linda', 'lindo',
  'aff', 'nossa', 'puts', 'putz',
  'vapt vupt', 'vapt-vupt',
  'naquele pique', 'no pique',
  'suave na nave', 'suave',
  'de boa', 'de buenas', 'na paz',
  'que nada', 'que isso', 'qual o quê', 'qual o que',
  'oxalá', 'oxala',
  'virgem', 'virgem maria',
  'barbaridade', 'barbaridade',
  'tchê', 'che', 'tche', 'gurizada',
  'capaz', 'capaz',
  'bah', 'ba', 'tchau',
  'até logo', 'ate logo', 'falou', 'flw',
  'brigado', 'brigada', 'valeu', 'vlw',
  'fui', 'tmj', 'tamo junto',
  'deixa quieto', 'deixa pra lá', 'deixa pra la',
  'relaxa', 'tranquilo', 'tranquila',
  'sem estresse', 'sem stress',
  'pega leve', 'pega leva',
  'se pá', 'se pa',
  'capaz', 'capaz',
  'demorô', 'demoro', 'fechou', 'fecho',
  'combinado', 'combinado',
  'vambora', 'bora', 'vamos embora',
  'desenrola', 'desenrolar', 'desenrolado',
  'se vira', 'se virar', 'se vire',
  'farinha pouca', 'farinha pouca',
  'em cima da hora', 'em cima da hora',
  'pagar mico', 'pagar mico',
  'fazer nas coxas', 'feito nas coxas',
  'mão na roda', 'mao na roda',
  'encher o saco', 'enche o saco',
  'encher o linguíça', 'encher a linguiça',
  'encher a paciência', 'encher a paciencia',
  'mala sem alça', 'mala sem alca',
  'mala', 'mala',
  'sem noção', 'sem nocao',
  'sem cabimento', 'sem cabimento',
  'fora de contexto', 'fora de contexto',
  'fora da casinha', 'fora da casinha',
  'pirado', 'pirada',
  'bitolado', 'bitolada',
  'aloprado', 'aloprada',
  'avacalhar', 'avacalhado', 'avacalhada',
  'zuar', 'zoar', 'zueira', 'zoera',
  'zoeira', 'zoiara', 'zuado', 'zuada',
  'sacangem', 'sacagem', 'sacanagem',
  'vacilo', 'vacilou', 'vacilão', 'vacilona',
  'mancada', 'mancada',
  'pisar na bola', 'pisou na bola',
  'dar mole', 'deu mole',
  'dar bobeira', 'deu bobeira',
  'cochilar', 'cochilou',
  'bater perna', 'batendo perna',
  'andar a toa', 'andar à toa',
  'na flauta', 'na flauta',
  'levar na flauta', 'leva na flauta',
  'levar na brincadeira', 'leva na brincadeira',
  'fazer pouco caso', 'fez pouco caso',
  'tirar sarro', 'tirou sarro', 'tira sarro',
  'caçoar', 'caçoando',
  'gozar', 'gozando', 'gozação', 'gozacao',
  'mangar', 'mangando', 'manga', 'manga',
]);

export function classifyRegister(token: string): 'formal' | 'informal' | null {
  const lower = token.toLowerCase();
  if (FORMAL_MARKERS.has(lower)) return 'formal';
  if (INFORMAL_MARKERS.has(lower)) return 'informal';
  return null;
}
