export const FORMAL_MARKERS = new Set([
  'portanto', 'entretanto', 'todavia', 'contudo', 'outrossim',
  'ademais', 'outrem', 'alhures', 'doravante',
  'outrora', 'sobejo', 'escopro', 'lusco-fusco', 'alva',
  'conquanto', 'destarte', 'dessarte', 'sobreditos',
  'supracitado', 'sobredito', 'epígrafe', 'epigrafe',
  'consoante', 'mormente', 'sobremaneira',
  'vossemecê', 'vossa', 'vosso', 'vossos', 'vossas',
  'merce', 'imperioso', 'imprescindível', 'imprescindivel',
  'notório', 'notoria', 'consubstanciado', 'consubstanciada',
  'hodierno', 'hodierna', 'litúrgico', 'liturgico',
  'sacrossanto', 'sacrossanta',
  'outrossim', 'ressalvado', 'ressalvada',
  'conquanto', 'malgrado', 'tampouco',
  'não obstante', 'nao obstante',
  'isto é', 'isto e',
  'ou seja',
  'porquanto', 'haja vista',
  'hajam vista', 'em tempo', 'outrossim',
  'a saber', 'verbis', 'ipsis litteris',
  'data venia', 'data vênia',
  'ad argumentandum', 'ad absurdum',
  'com efeito', 'com efeito',
  'dessa feita', 'desta feita',
  'à luz de', 'a luz de',
  'no tocante a', 'no tocante a',
  'com vistas a', 'com vistas a',
  'faz-se mister', 'faz-se mister',
  'cumpre salientar', 'cumpre salientar',
  'importa ressaltar', 'importa ressaltar',
  'deveras', 'sobreleva',
  'sobreleva notar', 'sobreleva notar',
  'venerando', 'veneranda',
  'egrégio', 'egregio', 'egrégia', 'egregia',
  'ilustríssimo', 'ilustrissimo', 'ilustríssima', 'ilustrissima',
  'excelentíssimo', 'excelentissimo',
  'douto', 'douta', 'insigne',
  'preclaro', 'preclara', 'ímprobo', 'improba',
  'abnegado', 'abnegada', 'probo', 'proba',
  'retidão', 'retidao', 'retitude',
  'proceder', 'procedimento',
  'exordial', 'procuração', 'procuração',
  'mandato', 'mandatário', 'mandataria',
  'despacho', 'sentença', 'sentenca',
  'acórdão', 'acordao', 'jurisprudência', 'jurisprudencia',
  'parecer', 'relatório', 'relatorio',
  'voto', 'vista', 'diligência', 'diligencia',
  'intimação', 'intimacao', 'citação', 'citacao',
  'notificação', 'notificacao',
  'convocação', 'convocacao',
  'destarte', 'desse jeito', 'desse modo',
  'dessa maneira', 'dessa forma',
  'sobejamente', 'sobejamente',
  'à toda evidência', 'a toda evidencia',
  'por derradeiro', 'em derradeiro',
  'ao cabo', 'ao fim e ao cabo',
  'em suma', 'em síntese', 'em sintese',
  'via de regra', 'via de regra',
  'não raro', 'nao raro',
  'não obstante', 'nao obstante',
  'tanto é assim que', 'tanto e assim que',
  'com efeito', 'com efeito',
  'por sinal', 'por sinal',
  'aliás', 'alias',
  'demais', 'igualmente',
  'dessarte', 'dessarte',
  'doutrina', 'doutrinário', 'doutrinaria',
  'teor', 'teor',
  'escopo', 'escopo',
  'cerne', 'cerne',
  'âmago', 'amago',
  'cerne da questão', 'cerne da questao',
  'fulcro', 'fulcro',
  'liame', 'liame',
  'vínculo', 'vinculo', 'nexo',
  'intuito', 'intento',
  'desiderato', 'desiderato',
  'condão', 'condao',
  'quilate', 'quilate',
  'estirpe', 'estirpe',
  'casta', 'casta',
  'prole', 'prole',
  'descendência', 'descendencia',
  'linhagem', 'linhagem',
  'in arábias', 'arabias',
  'combalido', 'combalida',
  'decrepitude', 'decrepitude',
  'senectude', 'senectude',
  'obsolescência', 'obsolescencia',
  'obsoleto', 'obsoleta',
  'caduco', 'caduca',
  'peremptório', 'peremptorio',
  'inconcuso', 'inconcussa',
  'indubitável', 'indubitavel', 'indubitavelmente',
  'inexorável', 'inexoravel', 'inexoravelmente',
  'inconteste', 'inconteste',
  'insofismável', 'insofismavel',
  'irretorquível', 'irretorquivel',
  'irrefragável', 'irrefragavel',
  'inilidível', 'inilidivel',
]);

export const INFORMAL_MARKERS = new Set([
  'tá', 'pra', 'pro', 'cê', 'né', 'tô', 'vô', 'tava',
  'numa', 'duma', 'mode', 'cuma', 'daí', 'dai',
  'aí', 'ai', 'ih', 'ah', 'ué', 'poxa',
  'mermo', 'trem', 'bão', 'sô', 'sôr',
  'beleza', 'brother', 'mana', 'miga', 'migo',
  'tipo', 'tlgd', 'se liga', 'vacilou', 'vacilo',
  'trampo', 'parada', 'nego', 'minina', 'mininu',
  'caba', 'muié', 'home', 'fessô', 'fessora',
  'oxente', 'visse', 'óia', 'ói', 'uai', 'eita',
  'nóis', 'nois', 'ocê', 'oces', 'cês', 'ces',
  'vixe', 'nossa', 'caraca', 'caramba',
  'pô', 'po', 'bá', 'bah',
  'tri', 'trilegal', 'da hora',
  'supimpa', 'sinistro', 'sinistra',
  'maneiro', 'maneira', 'bacana',
  'legal', 'fixe', 'giro', 'giro',
  'bué', 'bué', 'bué',
  'fixola', 'top', 'topzera',
  'brabo', 'braba', 'monstro',
  'monstra', 'fera', 'fodástico', 'fodastico',
  'foda', 'foda', 'foda-se', 'foda se',
  'porra', 'merda', 'bosta', 'cacete',
  'caralho', 'pau', 'rola', 'buceta',
  'arrombado', 'arrombada', 'filho da puta',
  'desgraçado', 'desgracado', 'desgraçada', 'desgracada',
  'babaca', 'otário', 'otario', 'otária', 'otaria',
  'idiota', 'imbecil', 'retardado', 'retardada',
  'maluquete', 'doido', 'doida', 'doidão', 'doidona',
  'véio', 'véia', 'veio', 'veia',
  'guri', 'guria', 'piá', 'pia',
  'moleque', 'moleca', 'pirralho', 'pirralha',
  'nego', 'nega', 'criolo', 'criola',
  'brother', 'brothers', 'mano', 'mana',
  'parceiro', 'parceira', 'parça', 'parcas',
  'amigão', 'amigona', 'chegado', 'chegada',
  'coé', 'coe', 'qualé', 'quale',
  'tô ligado', 'to ligado', 'tô ligada', 'to ligada',
  'entendeu', 'entende', 'saca', 'sacou',
  'tipo assim', 'tipo', 'assim tipo',
  'sei lá', 'sei la',
  'oravida', 'oravida',
  'véi', 'vei', 'cara',
  'mina', 'gata', 'gato', 'linda', 'lindo',
  'aff', 'nossa', 'puts', 'putz',
  'vapt vupt', 'vapt-vupt',
  'naquele pique', 'no pique',
  'suave na nave', 'suave',
  'de boa', 'de buenas', 'na paz',
  'que nada', 'que isso', 'qual o quê', 'qual o que',
  'oxalá', 'oxala',
  'virgem', 'virgem maria',
  'barbaridade', 'barbaridade',
  'tchê', 'che', 'tche', 'gurizada',
  'capaz', 'capaz',
  'bah', 'ba', 'tchau',
  'até logo', 'ate logo', 'falou', 'flw',
  'brigado', 'brigada', 'valeu', 'vlw',
  'fui', 'tmj', 'tamo junto',
  'deixa quieto', 'deixa pra lá', 'deixa pra la',
  'relaxa', 'tranquilo', 'tranquila',
  'sem estresse', 'sem stress',
  'pega leve', 'pega leva',
  'se pá', 'se pa',
  'capaz', 'capaz',
  'demorô', 'demoro', 'fechou', 'fecho',
  'combinado', 'combinado',
  'vambora', 'bora', 'vamos embora',
  'desenrola', 'desenrolar', 'desenrolado',
  'se vira', 'se virar', 'se vire',
  'farinha pouca', 'farinha pouca',
  'em cima da hora', 'em cima da hora',
  'pagar mico', 'pagar mico',
  'fazer nas coxas', 'feito nas coxas',
  'mão na roda', 'mao na roda',
  'encher o saco', 'enche o saco',
  'encher o linguíça', 'encher a linguiça',
  'encher a paciência', 'encher a paciencia',
  'mala sem alça', 'mala sem alca',
  'mala', 'mala',
  'sem noção', 'sem nocao',
  'sem cabimento', 'sem cabimento',
  'fora de contexto', 'fora de contexto',
  'fora da casinha', 'fora da casinha',
  'pirado', 'pirada',
  'bitolado', 'bitolada',
  'aloprado', 'aloprada',
  'avacalhar', 'avacalhado', 'avacalhada',
  'zuar', 'zoar', 'zueira', 'zoera',
  'zoeira', 'zoiara', 'zuado', 'zuada',
  'sacangem', 'sacagem', 'sacanagem',
  'vacilo', 'vacilou', 'vacilão', 'vacilona',
  'mancada', 'mancada',
  'pisar na bola', 'pisou na bola',
  'dar mole', 'deu mole',
  'dar bobeira', 'deu bobeira',
  'cochilar', 'cochilou',
  'bater perna', 'batendo perna',
  'andar a toa', 'andar à toa',
  'na flauta', 'na flauta',
  'levar na flauta', 'leva na flauta',
  'levar na brincadeira', 'leva na brincadeira',
  'fazer pouco caso', 'fez pouco caso',
  'tirar sarro', 'tirou sarro', 'tira sarro',
  'caçoar', 'caçoando',
  'gozar', 'gozando', 'gozação', 'gozacao',
  'mangar', 'mangando', 'manga', 'manga',
]);

export function classifyRegister(token: string): 'formal' | 'informal' | null {
  const lower = token.toLowerCase();
  if (FORMAL_MARKERS.has(lower)) return 'formal';
  if (INFORMAL_MARKERS.has(lower)) return 'informal';
  return null;
}
