export interface SentiLexEntry {
  lemma: string;
  polarity: -1 | 0 | 1;
  pos: 'ADJ' | 'N' | 'V' | 'IDIOM';
}

const RAW_LEXICON: Array<[string, -1 | 0 | 1, 'ADJ' | 'N' | 'V' | 'IDIOM']> = [
  ['amor', 1, 'N'],
  ['feliz', 1, 'ADJ'],
  ['felicidade', 1, 'N'],
  ['alegria', 1, 'N'],
  ['beleza', 1, 'N'],
  ['belo', 1, 'ADJ'],
  ['bela', 1, 'ADJ'],
  ['paz', 1, 'N'],
  ['esperança', 1, 'N'],
  ['esperanca', 0, 'N'],
  ['sonho', 1, 'N'],
  ['prazer', 1, 'N'],
  ['êxtase', 1, 'N'],
  ['extase', 1, 'N'],
  ['ternura', 1, 'N'],
  ['doce', 1, 'ADJ'],
  ['luz', 1, 'N'],
  ['glória', 1, 'N'],
  ['gloria', 1, 'N'],
  ['sublime', 1, 'ADJ'],
  ['plenitude', 1, 'N'],
  ['encanto', 1, 'N'],
  ['divino', 1, 'ADJ'],
  ['paraíso', 1, 'N'],
  ['paraiso', 1, 'N'],
  ['júbilo', 1, 'N'],
  ['jubilo', 1, 'N'],
  ['exultação', 1, 'N'],
  ['exultacao', 1, 'N'],
  ['riso', 1, 'N'],
  ['canto', 1, 'N'],
  ['festa', 1, 'N'],
  ['celebração', 1, 'N'],
  ['celebraçao', 1, 'N'],
  ['abundância', 1, 'N'],
  ['abundancia', 1, 'N'],
  ['alvorada', 1, 'N'],
  ['dourado', 1, 'ADJ'],
  ['vivo', 1, 'ADJ'],
  ['viva', 1, 'ADJ'],
  ['brilho', 1, 'N'],
  ['maravilha', 1, 'N'],
  ['magnífico', 1, 'ADJ'],
  ['magnifico', 1, 'ADJ'],
  ['eterno', 1, 'ADJ'],
  ['eterna', 1, 'ADJ'],
  ['infinito', 1, 'ADJ'],
  ['infinita', 1, 'ADJ'],
  ['liberdade', 1, 'N'],
  ['leve', 1, 'ADJ'],
  ['suave', 1, 'ADJ'],
  ['terno', 1, 'ADJ'],
  ['terna', 1, 'ADJ'],
  ['puro', 1, 'ADJ'],
  ['pura', 1, 'ADJ'],
  ['doçura', 1, 'N'],
  ['docura', 1, 'N'],
  ['carinho', 1, 'N'],
  ['afeto', 1, 'N'],
  ['afeicao', 1, 'N'],
  ['afeição', 1, 'N'],
  ['delícia', 1, 'N'],
  ['delicia', 1, 'N'],
  ['harmonia', 1, 'N'],
  ['graça', 1, 'N'],
  ['graca', 1, 'N'],
  ['sabor', 1, 'N'],
  ['calma', 1, 'ADJ'],
  ['sereno', 1, 'ADJ'],
  ['serena', 1, 'ADJ'],
  ['transcendência', 1, 'N'],
  ['transcendencia', 1, 'N'],
  ['milagre', 1, 'N'],
  ['redenção', 1, 'N'],
  ['redencao', 1, 'N'],
  ['perdão', 1, 'N'],
  ['perdao', 1, 'N'],
  ['bênção', 1, 'N'],
  ['bencao', 1, 'N'],
  ['ninho', 1, 'N'],
  ['abrigo', 1, 'N'],
  ['ventura', 1, 'N'],
  ['sortilégio', 1, 'N'],
  ['sortilegio', 1, 'N'],
  ['esplendor', 1, 'N'],
  ['faisca', 1, 'N'],
  ['faísca', 1, 'N'],

  ['dor', -1, 'N'],
  ['triste', -1, 'ADJ'],
  ['tristeza', -1, 'N'],
  ['morte', -1, 'N'],
  ['medo', -1, 'N'],
  ['horror', -1, 'N'],
  ['angústia', -1, 'N'],
  ['angustia', -1, 'N'],
  ['sofrimento', -1, 'N'],
  ['lágrima', -1, 'N'],
  ['lagrima', -1, 'N'],
  ['pranto', -1, 'N'],
  ['solidão', -1, 'N'],
  ['solidao', -1, 'N'],
  ['desespero', -1, 'N'],
  ['ódio', -1, 'N'],
  ['odio', -1, 'N'],
  ['rancor', -1, 'N'],
  ['culpa', -1, 'N'],
  ['vergonha', -1, 'N'],
  ['nojo', -1, 'N'],
  ['luto', -1, 'N'],
  ['silêncio', -1, 'N'],
  ['silêncio', -1, 'N'],
  ['sombra', -1, 'N'],
  ['treva', -1, 'N'],
  ['ruína', -1, 'N'],
  ['ruina', -1, 'N'],
  ['mágoa', -1, 'N'],
  ['magoa', -1, 'N'],
  ['saudade', -1, 'N'],
  ['pesar', -1, 'N'],
  ['ermo', -1, 'N'],
  ['langor', -1, 'N'],
  ['soturno', -1, 'ADJ'],
  ['lívido', -1, 'ADJ'],
  ['livido', -1, 'ADJ'],
  ['funéreo', -1, 'ADJ'],
  ['funereo', -1, 'ADJ'],
  ['opaco', -1, 'ADJ'],
  ['vazio', -1, 'ADJ'],
  ['vazia', -1, 'ADJ'],
  ['ausência', -1, 'N'],
  ['ausencia', -1, 'N'],
  ['perda', -1, 'N'],
  ['falta', -1, 'N'],
  ['exílio', -1, 'N'],
  ['exilio', -1, 'N'],
  ['cemitério', -1, 'N'],
  ['cemiterio', -1, 'N'],
  ['sepulcro', -1, 'N'],
  ['tumba', -1, 'N'],
  ['podridão', -1, 'N'],
  ['podridao', -1, 'N'],
  ['verme', -1, 'N'],
  ['espectro', -1, 'N'],
  ['abismo', -1, 'N'],
  ['maldição', -1, 'N'],
  ['maldicao', -1, 'N'],
  ['preságio', -1, 'N'],
  ['presagio', -1, 'N'],
  ['sangue', -1, 'N'],
  ['monstro', -1, 'N'],
  ['escuro', -1, 'ADJ'],
  ['escura', -1, 'ADJ'],
  ['frio', -1, 'ADJ'],
  ['fria', -1, 'ADJ'],
  ['amargo', -1, 'ADJ'],
  ['amarga', -1, 'ADJ'],
  ['cruel', -1, 'ADJ'],
  ['pálido', -1, 'ADJ'],
  ['palido', -1, 'ADJ'],
  ['lamento', -1, 'N'],
  ['gemido', -1, 'N'],
  ['choro', -1, 'N'],
  ['choro', -1, 'V'],
  ['agonia', -1, 'N'],
  ['tormento', -1, 'N'],
  ['suplício', -1, 'N'],
  ['suplicio', -1, 'N'],
  ['inferno', -1, 'N'],
  ['demônio', -1, 'N'],
  ['demonio', -1, 'N'],
  ['pecado', -1, 'N'],
  ['degeneraçao', -1, 'N'],
  ['degeneração', -1, 'N'],
  ['lodo', -1, 'N'],
  ['charco', -1, 'N'],
  ['necrose', -1, 'N'],
  ['carniça', -1, 'N'],
  ['carnica', -1, 'N'],
  ['desgraça', -1, 'N'],
  ['desgraca', -1, 'N'],
  ['desalento', -1, 'N'],
  ['desilusão', -1, 'N'],
  ['desilusao', -1, 'N'],
  ['náusea', -1, 'N'],
  ['nausea', -1, 'N'],

  ['vida', 0, 'N'],
  ['tempo', 0, 'N'],
  ['mundo', 0, 'N'],
  ['alma', 0, 'N'],
  ['coração', 0, 'N'],
  ['coracao', 0, 'N'],
  ['mente', 0, 'N'],
  ['corpo', 0, 'N'],
  ['céu', 0, 'N'],
  ['ceu', 0, 'N'],
  ['mar', 0, 'N'],
  ['terra', 0, 'N'],
  ['vento', 0, 'N'],
  ['fogo', 0, 'N'],
  ['água', 0, 'N'],
  ['agua', 0, 'N'],
  ['pedra', 0, 'N'],
  ['dia', 0, 'N'],
  ['noite', 0, 'N'],
  ['sol', 0, 'N'],
  ['lua', 0, 'N'],
  ['estrela', 0, 'N'],
  ['árvore', 0, 'N'],
  ['arvore', 0, 'N'],
  ['flor', 0, 'N'],
  ['rio', 0, 'N'],
  ['montanha', 0, 'N'],
  ['campo', 0, 'N'],
  ['jardim', 0, 'N'],
  ['casa', 0, 'N'],
  ['porta', 0, 'N'],
  ['janela', 0, 'N'],
  ['mesa', 0, 'N'],
  ['cadeira', 0, 'N'],
  ['cama', 0, 'N'],
  ['olho', 0, 'N'],
  ['mão', 0, 'N'],
  ['mao', 0, 'N'],
  ['rosto', 0, 'N'],
  ['boca', 0, 'N'],
  ['pele', 0, 'N'],
  ['cabelo', 0, 'N'],
  ['sangue', 0, 'N'],
  ['osso', 0, 'N'],
  ['carne', 0, 'N'],
  ['espírito', 0, 'N'],
  ['espirito', 0, 'N'],
  ['memória', 0, 'N'],
  ['memoria', 0, 'N'],
  ['infância', 0, 'N'],
  ['infancia', 0, 'N'],
  ['passado', 0, 'N'],
  ['futuro', 0, 'N'],
  ['presente', 0, 'N'],
  ['destino', 0, 'N'],
  ['acaso', 0, 'N'],
  ['sorte', 0, 'N'],
  ['enigma', 0, 'N'],
  ['mistério', 0, 'N'],
  ['misterio', 0, 'N'],
  ['eternidade', 0, 'N'],
  ['origem', 0, 'N'],
  ['criação', 0, 'N'],
  ['criacao', 0, 'N'],
  ['cosmos', 0, 'N'],
  ['universo', 0, 'N'],
  ['natureza', 0, 'N'],
  ['poesia', 0, 'N'],
  ['poema', 0, 'N'],
  ['verso', 0, 'N'],
  ['palavra', 0, 'N'],
  ['canto', 0, 'N'],
  ['lágrima', 0, 'N'],
  ['musa', 0, 'N'],
  ['fonte', 0, 'N'],
  ['chama', 0, 'N'],
  ['brasa', 0, 'N'],
  ['espelho', 0, 'N'],
  ['véu', 0, 'N'],
  ['veu', 0, 'N'],
  ['eco', 0, 'N'],
  ['rastro', 0, 'N'],
  ['pegada', 0, 'N'],
  ['nuvem', 0, 'N'],
  ['chuva', 0, 'N'],
  ['neve', 0, 'N'],
  ['gelo', 0, 'N'],
  ['vela', 0, 'N'],
  ['candeia', 0, 'N'],
  ['lâmpada', 0, 'N'],
  ['lampada', 0, 'N'],
  ['caminho', 0, 'N'],
  ['estrada', 0, 'N'],
  ['ponte', 0, 'N'],
  ['muro', 0, 'N'],
  ['grade', 0, 'N'],
  ['chave', 0, 'N'],
  ['cadeado', 0, 'N'],
  ['caixa', 0, 'N'],
  ['baú', 0, 'N'],
  ['bau', 0, 'N'],
  ['tesouro', 0, 'N'],
  ['barco', 0, 'N'],
  ['navio', 0, 'N'],
  ['vela', 0, 'N'],
  ['remo', 0, 'N'],
  ['âncora', 0, 'N'],
  ['ancora', 0, 'N'],
  ['ilha', 0, 'N'],
  ['praia', 0, 'N'],
  ['onda', 0, 'N'],
  ['areia', 0, 'N'],
  ['concha', 0, 'N'],
  ['pérola', 0, 'N'],
  ['perola', 0, 'N'],
];

function buildLexicon(): Map<string, SentiLexEntry> {
  const map = new Map<string, SentiLexEntry>();
  for (const [lemma, polarity, pos] of RAW_LEXICON) {
    map.set(lemma, { lemma, polarity, pos });
  }
  return map;
}

const LEXICON = buildLexicon();

export function getSentiment(word: string): SentiLexEntry | undefined {
  return LEXICON.get(word.toLowerCase());
}

export function analyzeSentiment(tokens: string[]): {
  positiveRatio: number;
  negativeRatio: number;
  neutralRatio: number;
  compoundScore: number;
  dominantEmotion: string;
} {
  let pos = 0, neg = 0, neu = 0;
  for (const token of tokens) {
    const entry = LEXICON.get(token.toLowerCase());
    if (!entry) { neu++; continue; }
    if (entry.polarity === 1) pos++;
    else if (entry.polarity === -1) neg++;
    else neu++;
  }
  const total = pos + neg + neu || 1;
  const compoundScore = (pos - neg) / total;
  const dominantEmotion = pos > neg ? 'positivo' : neg > pos ? 'negativo' : 'neutro';
  return {
    positiveRatio: pos / total,
    negativeRatio: neg / total,
    neutralRatio: neu / total,
    compoundScore,
    dominantEmotion,
  };
}
